#!/bin/sh
DOCKER_VERSION='17.03.2~ce-0~ubuntu-xenial' # newest docker officially supported by kubernetes 1.9

apt-get update
apt-get -y install apt-transport-https ca-certificates neovim vim nano htop git ack-grep

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# sudo add-apt-repository \
#    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
#    $(lsb_release -cs) \
#    stable test"

# apt-get update

# install recommended packages
apt-get install -y python

# install Docker
apt-get install -y docker-ce=${DOCKER_VERSION}

mkdir /root/workshop

git clone https://github.com/McSlow/k8s_flask  /root/workshop/simple_flask
git clone https://github.com/McSlow/k8s_objects /root/workshop/objects
# add IP to environment variable
echo "export IP=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1 | head -n 1)" >> /root/.bashrc
